### ISSUE TITLE
[BUG] "Open with picker" w/ blank query

### ISSUE THREAD

**Issue by cibere** [NoPlagiarism/FlowTamer#1]
Hello @NoPlagiarism!

With a blank query, just `bt`, clicking the `Open` result works as expected, and opens the BrowserTamer application. However when I click the `Open with picker` result, I expected it to open up the picker to start a browser, however instead it opened up `pick` in my default browser.

<img width="779" alt="Flow Launcher_XFSNTFxtqu" src="https://github.com/user-attachments/assets/ff4cadc8-de35-45a1-8aea-e123575f8a44">
<img width="769" alt="firefox_nJer2HPotW" src="https://github.com/user-attachments/assets/f6ea39ab-eee7-4c19-932a-d0ae66be1097">

**Comment by NoPlagiarism** [comment]
Thanks for reaching out. Should be fixed with next release
